version: "3.0"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=xendit-test
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/xendit-test?sslmode=disable
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "/app/main"]
