// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID             int32
	UserID         sql.NullInt32
	OrganizationID int32
	Text           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type Membership struct {
	UserID         int32
	OrganizationID int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}

type Organization struct {
	ID        int32
	Login     string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type User struct {
	ID        int32
	Login     string
	Name      string
	Followers int32
	Follows   int32
	AvatarUrl sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
