// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateCommentByOrganizationLogin(ctx context.Context, arg CreateCommentByOrganizationLoginParams) (Comment, error)
	DeleteCommentsByOrganizationLogin(ctx context.Context, login string) error
	ListCommentsByOrganizationLogin(ctx context.Context, arg ListCommentsByOrganizationLoginParams) ([]Comment, error)
	ListUsersByOrganizationLogin(ctx context.Context, arg ListUsersByOrganizationLoginParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
